function [x, y, u] = importdata(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  [X, Y, U] = IMPORTDATA(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as column vectors.
%
%  [X, Y, U] = IMPORTDATA(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  [x, y, u] = importdata("results_serial.dat", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Mar-2022 12:21:39

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["x", "y", "u"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
x = tbl.x;
y = tbl.y;
u = tbl.u;
end